import jsPDF from "jspdf";

interface QuizQuestion {
  question: string;
  options: string[];
  correctOptionIndex: number;
  explanation?: string;
}

interface QuizData {
  title: string;
  questions: QuizQuestion[];
  createdAt: string;
  telegramChannel?: string | null;
}

export function exportQuizAsPDF(quiz: QuizData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
    drawHeader();
  };

  const checkPage = (needed: number) => {
    if (y + needed > pageH - margin) addPage();
  };

  const drawHeader = () => {
    doc.setFillColor(0, 123, 110);
    doc.rect(0, 0, pageW, 12, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Telegram Quiz Generator", margin, 8);
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageW - margin, 8, { align: "right" });
    doc.setTextColor(0, 0, 0);
    y = Math.max(y, 16);
  };

  drawHeader();

  doc.setFillColor(0, 123, 110);
  doc.rect(margin - 2, y - 2, contentW + 4, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  const titleLines = doc.splitTextToSize(quiz.title, contentW - 4);
  doc.text(titleLines, margin + 1, y + 7);
  y += titleLines.length * 7 + 6;

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const dateStr = new Date(quiz.createdAt).toLocaleDateString("en-GB", {
    year: "numeric", month: "long", day: "numeric"
  });
  doc.text(`${quiz.questions.length} Questions  •  Generated: ${dateStr}${quiz.telegramChannel ? `  •  Channel: ${quiz.telegramChannel}` : ""}`, margin, y);
  y += 8;

  doc.setDrawColor(0, 123, 110);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  quiz.questions.forEach((q, i) => {
    const optionLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];

    const qLines = doc.splitTextToSize(`Q${i + 1}. ${q.question}`, contentW - 8);
    const optionBlocks = q.options.map((opt, j) => {
      const lines = doc.splitTextToSize(`${optionLetters[j]}. ${opt}`, contentW - 16);
      return { lines, isCorrect: j === q.correctOptionIndex };
    });
    const expLines = q.explanation
      ? doc.splitTextToSize(`Explanation: ${q.explanation}`, contentW - 8)
      : [];

    const blockH = 6 + qLines.length * 5.5 + optionBlocks.reduce((s, b) => s + b.lines.length * 4.5 + 2, 0) + (expLines.length > 0 ? expLines.length * 4.5 + 6 : 0) + 6;
    checkPage(blockH);

    doc.setFillColor(245, 245, 245);
    doc.setDrawColor(220, 220, 220);
    doc.roundedRect(margin - 2, y - 1, contentW + 4, blockH, 2, 2, "FD");

    doc.setFillColor(0, 123, 110);
    doc.circle(margin + 3, y + 3.5, 3.5, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}`, margin + 3, y + 4.2, { align: "center" });

    doc.setTextColor(20, 20, 20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(qLines, margin + 8, y + 4);
    y += qLines.length * 5.5 + 4;

    optionBlocks.forEach(({ lines, isCorrect }) => {
      if (isCorrect) {
        doc.setFillColor(209, 250, 229);
        doc.setDrawColor(16, 185, 129);
        doc.roundedRect(margin + 4, y - 0.5, contentW - 6, lines.length * 4.5 + 1.5, 1, 1, "FD");
        doc.setTextColor(6, 95, 70);
        doc.setFont("helvetica", "bold");
      } else {
        doc.setTextColor(60, 60, 60);
        doc.setFont("helvetica", "normal");
      }
      doc.setFontSize(9);
      doc.text(lines, margin + 8, y + 3);
      if (isCorrect) {
        doc.setFontSize(8);
        doc.text("✓", pageW - margin - 6, y + 3);
      }
      y += lines.length * 4.5 + 2;
    });

    if (expLines.length > 0) {
      y += 2;
      doc.setFillColor(239, 246, 255);
      doc.setDrawColor(147, 197, 253);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin + 2, y - 1, contentW - 2, expLines.length * 4.5 + 3, 1, 1, "FD");
      doc.setTextColor(29, 78, 216);
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "italic");
      doc.text(expLines, margin + 5, y + 2.5);
      y += expLines.length * 4.5 + 4;
    }

    y += 6;
  });

  const totalPages = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(240, 240, 240);
    doc.rect(0, pageH - 10, pageW, 10, "F");
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by Telegram Quiz Generator", margin, pageH - 3.5);
    doc.text(`${i} / ${totalPages}`, pageW - margin, pageH - 3.5, { align: "right" });
  }

  doc.save(`${quiz.title.replace(/[^a-zA-Z0-9\s]/g, "").trim() || "quiz"}.pdf`);
}
